// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZAXmk1Cwfpjc0zuNjpStauwLRb_O7OKE',
    appId: '1:364272834994:android:bc2ec43f0c997deca5ecab',
    messagingSenderId: '364272834994',
    projectId: 'vision-aid-app-b693f',
    databaseURL: 'https://vision-aid-app-b693f-default-rtdb.firebaseio.com',
    storageBucket: 'vision-aid-app-b693f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwGmwL1crtLyaq5O88t6M5zUBRF4L_zdU',
    appId: '1:364272834994:ios:b7163c0e134ddb2fa5ecab',
    messagingSenderId: '364272834994',
    projectId: 'vision-aid-app-b693f',
    databaseURL: 'https://vision-aid-app-b693f-default-rtdb.firebaseio.com',
    storageBucket: 'vision-aid-app-b693f.firebasestorage.app',
    iosBundleId: 'com.example.liveTrackerApp',
  );
}
